### ISSUE TITLE
Not able to control the picker with external button

### ISSUE THREAD

**Issue by sunpietro** [haoxins/react-flatpickr#178] opened 2022-02-23 11:34 UTC
Hi, I'm trying to control the Flatpickr expanded state with external button like this:
```jsx
import { useRef } from 'react';
import Flatpickr from 'react-flatpickr';
import flatpickr from 'flatpickr';

flatpickr.l10ns.default.firstDayOfWeek = 1;

export const DatePicker = (): JSX.Element => {
  const pickerRef = useRef<Flatpickr | null>(null);
  const calendar = pickerRef?.current?.flatpickr;
  const isOpen = calendar?.isOpen;

  return (
    <div>
      <Flatpickr
        ref={pickerRef}
        options={{
          minDate: new Date(),
          dateFormat: 'd/m/Y',
        }}
      />
      <button
        type="button"
        onClick={!isOpen ? () => calendar?.open() : () => calendar?.close()}
        // onClick={() => calendar?.toggle()} <== it doesn't work as well
      >
        Click
      </button>
    </div>
  );
};
```
Unfortunately, only the first click on the "Click" button works as expected. It's opening the calendar view.
When I try to close it, then it closes and opens up again the calendar. I'm not sure how to control it properly. Any help would be appreciated.

**version: 3.10.7**

**Comment by jacobmischka** [comment] 2022-02-23 11:47
Clicking outside of the popup closes it automatically, so it's never actually open by the time the click handler is processed.

You can rely on this to handle closing it for you, or you can use something like the `inline` config option to refactor your input.

**Comment by sunpietro** [comment] 2022-02-23 12:31
So there's no way to add element detection at the current state, right?

**Comment by jacobmischka** [comment] 2022-02-23 12:46
I don't know what you mean by that, sorry.

Using `event.stopPropagation()` in your click handler will probably make it behave as you expect, though as I said you might as well just rely on the auto-close behavior.

Anyway, closing this because it's not a bug, or related to react-flatpickr at all I don't think.

**Closed by jacobmischka** 2022-02-23 12:46 UTC
